#!/usr/bin/env python3
"""Extract a Gira Windows installer, apply browser patches, and publish web/."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parent
DEFAULT_INSTALLER = "SmartHomeSetup_win32-x64-release-6.0.72.exe"
INSTALLER_URL = f"https://download.gira.de/data3/{DEFAULT_INSTALLER}"


def download_installer():
    destination = ROOT / DEFAULT_INSTALLER
    if destination.is_file():
        return destination
    print(f"Downloading {INSTALLER_URL}", flush=True)
    # Publish only a complete download so interrupted runs can safely retry.
    with tempfile.TemporaryDirectory(prefix=".gira-setup-", dir=ROOT) as directory:
        pending = Path(directory) / DEFAULT_INSTALLER
        with urlopen(INSTALLER_URL, timeout=60) as response, pending.open("wb") as stream:
            shutil.copyfileobj(response, stream)
            expected = response.headers.get("Content-Length")
        if expected is not None and pending.stat().st_size != int(expected):
            raise ValueError("Incomplete installer download; rerun setup to retry")
        with pending.open("rb") as stream:
            if stream.read(2) != b"MZ":
                raise ValueError("Downloaded file is not a Windows installer")
        pending.rename(destination)
    return destination


def digest(data):
    return hashlib.sha256(data).hexdigest()


def sha256(path):
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def extractor(explicit):
    requested = explicit or "innoextract"
    executable = shutil.which(requested)
    if not executable:
        raise ValueError(f"Cannot find {requested}. Install innoextract and add it to PATH, "
                         "or pass --innoextract /path/to/innoextract.")
    return executable


def contained_file(root, name):
    relative = Path(name)
    path = (root / relative).resolve()
    if relative.is_absolute() or not path.is_relative_to(root.resolve()):
        raise ValueError(f"Path escapes its root: {name}")
    return path


def apply_patches(web):
    directory = ROOT / "patches"
    series_data = (directory / "series.json").read_bytes()
    series = json.loads(series_data)
    if series.get("schema") != 1 or not series.get("patches"):
        raise ValueError("Unsupported or empty patch series")
    staged, original, records, identifiers = {}, {}, [], set()
    specifications = {"series.json": digest(series_data)}

    # Validate the entire series before writing. Exactly one literal match is
    # required so a changed upstream bundle cannot receive a guessed patch.
    for filename in series["patches"]:
        data = contained_file(directory, filename).read_bytes()
        spec = json.loads(data)
        identifier = spec["id"]
        if identifier in identifiers or not spec.get("edits"):
            raise ValueError(f"Duplicate or empty patch: {identifier}")
        identifiers.add(identifier)
        specifications[filename] = digest(data)
        files = []
        for edit in spec["edits"]:
            name = edit["file"]
            before, after = edit["before"].encode("utf-8"), edit["after"].encode("utf-8")
            if not before or b"\r" in after:
                raise ValueError(f"{identifier}: empty match or non-LF replacement")
            if name not in staged:
                staged[name] = original[name] = contained_file(web, name).read_bytes()
            count = staged[name].count(before)
            if count != 1:
                raise ValueError(f"Patch {identifier}: {name}: expected exactly 1 source match, found {count}. Review this installer; web/ is unchanged.")
            staged[name] = staged[name].replace(before, after, 1)
            files.append(name)
        records.append({"id": identifier, "reason": spec["reason"], "files": sorted(set(files))})
    for name, data in staged.items():
        contained_file(web, name).write_bytes(data)
    return {"schema": 1, "tested_versions": series.get("tested_versions", []),
            "specifications": specifications, "applied": records,
            "modified_files": {name: {"before_sha256": digest(original[name]), "after_sha256": digest(data)}
                               for name, data in sorted(staged.items())}}


def build(installer, executable):
    output = ROOT / "web"
    if output.exists() or output.is_symlink():
        manifest = output / "build-manifest.json"
        if output.is_symlink() or not manifest.is_file() or json.loads(manifest.read_text(encoding="utf-8")).get("generator") != "gira-web-setup":
            raise ValueError("Refusing to replace web/: it was not generated by setup.py")

    # Extraction, patching, and validation happen in a temporary workspace.
    # Publish only after success; keep the old web root just long enough to
    # roll back a failed rename, then remove it rather than accumulating backups.
    with tempfile.TemporaryDirectory(prefix=".gira-setup-", dir=ROOT) as directory:
        temp = Path(directory)
        unpacked, stage = temp / "extracted", temp / "web"
        subprocess.run([executable, "--silent", "--output-dir", str(unpacked), str(installer)], check=True)
        candidates = []
        for package_path in unpacked.rglob("package.json"):
            if "node_modules" in package_path.parts:
                continue
            for layout in package_path.parent.rglob("layout.html"):
                if "node_modules" not in layout.parts and (layout.parent / "layout.loader.js").is_file():
                    candidates.append((layout.parent, json.loads(package_path.read_text(encoding="utf-8"))))
        if len(candidates) != 1:
            raise ValueError(f"Expected one web app, found {len(candidates)}; review the installer layout")
        source, package = candidates[0]
        if any(path.is_symlink() for path in source.rglob("*")):
            raise ValueError("Unexpected symlink in web assets")
        bundle = (source / "layout.loader.js").read_text(encoding="utf-8")
        for marker in ("class CoreDesktopApi", "localStorage.getItem", "localStorage.setItem", "/gds/api"):
            if marker not in bundle:
                raise ValueError(f"Browser compatibility marker changed: {marker}")
        shutil.copytree(source, stage)
        patches = apply_patches(stage)
        for reserved in ("index.html", "build-manifest.json"):
            if (stage / reserved).exists():
                raise ValueError(f"Upstream contains {reserved}; review entry-page generation")
        version = json.dumps(str(package["version"])).replace("<", "\\u003c")
        (stage / "index.html").write_text('''<!doctype html>
<html lang="en"><meta charset="utf-8"><title>Gira Smart Home</title>
<script>
const target = new URL("layout.html", location.href);
target.search = location.search;
const language = target.searchParams.get("osLanguage") || navigator.language.split("-")[0];
if (!localStorage.getItem("defaultLanguage")) localStorage.setItem("defaultLanguage", language);
target.searchParams.set("osLanguage", language);
target.searchParams.set("version", ''' + version + ''');
location.replace(target);
</script>
<noscript>This application requires JavaScript.</noscript></html>
''', encoding="utf-8", newline="\n")
        manifest = {"generator": "gira-web-setup", "app_version": package["version"],
                    "patch_set": patches, "installer": installer.name,
                    "installer_sha256": sha256(installer),
                    "extractor_version": subprocess.check_output([executable, "--version"], text=True).strip(),
                    "files": {str(p.relative_to(stage)): sha256(p) for p in sorted(stage.rglob("*")) if p.is_file()}}
        (stage / "build-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
        previous = temp / "previous"
        if output.exists():
            output.rename(previous)
        try:
            stage.rename(output)
        except BaseException:
            if previous.exists():
                previous.rename(output)
            raise
    print(f"Built {package['version']} in web/ with {len(patches['applied'])} patches.")
    if package["version"] not in patches["tested_versions"]:
        print("This version has not been browser-tested; verify it against your device.")
    print("Run: python3 server.py")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("installer", nargs="?", type=Path,
                        help="Use the sole .exe beside this script, or download Gira 6.0.72 if none exists")
    parser.add_argument("--innoextract", default=os.environ.get("INNOEXTRACT"), help="Use an existing extractor")
    args = parser.parse_args()
    try:
        executable = extractor(args.innoextract)
        installer = args.installer
        if installer is None:
            installers = sorted(ROOT.glob("*.exe"))
            if len(installers) > 1:
                raise ValueError("Specify an installer: python3 setup.py /path/to/SmartHomeSetup.exe")
            installer = installers[0] if installers else download_installer()
        installer = installer.resolve(strict=True)
        build(installer, executable)
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"Error: {error}\n")


if __name__ == "__main__":
    main()
